# Generated by Django 5.1.6 on 2025-03-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreunion',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
